# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04e3c022d791802baab0604054f373d0be3924e624e2085f9d7112ace9bc823115a772c33fdce05470227fc0096b8e7d2920ad374a43d36e5511b606402831c2

test:
  secret_key_base: 48e0911b49031ddbc0d3a1d507ac86cddefd7423566d0572a579694d16b4f4fb0cb4fb6d16befba4c1bae2086a1fe970bb27001f8a8485d02c3d3a7e4035ba54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
